name = "perforated-panel-designer"
compatibility_date = "2024-01-01"

[env.production]
vars = { ADMIN_USERNAME = "admin", ADMIN_PASSWORD = "AdminEhsan092161!@#", SUPERADMIN_EMAIL = "Ehsan0921@gmail.com" }

[env.preview]
vars = { ADMIN_USERNAME = "admin", ADMIN_PASSWORD = "AdminEhsan092161!@#", SUPERADMIN_EMAIL = "Ehsan0921@gmail.com" }
